import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { describe, it } from "node:test";

describe("TikTok caption overlay style", () => {
  it("styles Chinese captions, warning, potential states, and resize affordance", async () => {
    const css = await readFile("extension/src/tiktokCaptionOverlay.css", "utf8");
    const source = await readFile("extension/src/tiktokCaptionCore.js", "utf8");

    assert.match(css, /\.msj-tiktok-caption-translation\s*{[\s\S]*color:\s*#000000/);
    assert.match(css, /\.msj-tiktok-caption-translation\s*{[\s\S]*font-weight:\s*800/);
    assert.match(css, /\.msj-tiktok-warning-badges\.is-visible\s*{[\s\S]*display:\s*flex/);
    assert.match(css, /\.msj-tiktok-warning-badge\s*{[\s\S]*color:\s*#d92d20/);
    assert.match(css, /\.msj-tiktok-potential\.is-high\s*{[\s\S]*color:\s*#d92d20/);
    assert.match(css, /\.msj-tiktok-potential\.is-mid\s*{[\s\S]*color:\s*#15803d/);
    assert.match(css, /\.msj-tiktok-potential\.is-low\s*{[\s\S]*color:\s*#6b7280/);
    assert.match(css, /\.msj-tiktok-caption-resize-handle\.is-top\s*{/);
    assert.match(css, /\.msj-tiktok-caption-resize-handle\.is-right\s*{/);
    assert.match(css, /\.msj-tiktok-caption-resize-handle\.is-bottom\s*{/);
    assert.match(css, /\.msj-tiktok-caption-resize-handle\.is-left\s*{/);
    assert.match(css, /\.msj-tiktok-video-info\s*{[\s\S]*display:\s*flex/);
    assert.match(css, /\.msj-tiktok-video-metric-icon\s*{/);
    assert.match(css, /\.msj-tiktok-video-details-resize\s*{/);
    assert.match(css, /grid-template-rows:\s*auto auto auto auto auto minmax\(0,\s*1fr\);/);
    assert.match(css, /\.msj-tiktok-caption-actions\s*{[\s\S]*flex-wrap:\s*nowrap/);
    assert.match(css, /\.msj-tiktok-caption-actions\s*{[\s\S]*position:\s*absolute/);
    assert.match(css, /\.msj-tiktok-caption-actions\s*{[\s\S]*bottom:\s*10px/);
    assert.match(css, /\.msj-tiktok-caption-actions \.msj-tiktok-caption-status\s*{[\s\S]*text-overflow:\s*ellipsis/);
    assert.match(css, /\.msj-tiktok-caption-action-button\s*{[\s\S]*flex:\s*0 0 auto/);
    assert.match(css, /\.msj-tiktok-caption-font-button\s*{[\s\S]*flex:\s*0 0 auto/);
    assert.match(css, /\.msj-tiktok-caption-list\s*{[\s\S]*padding:\s*10px 10px 58px/);
    assert.match(css, /\.msj-tiktok-caption-list\s*{[\s\S]*scroll-padding-bottom:\s*58px/);
    assert.match(css, /\.msj-tiktok-card-metrics\s*{[\s\S]*pointer-events:\s*none/);
    assert.match(css, /\.msj-tiktok-card-metric\s*{[\s\S]*background:\s*rgba\(236,\s*253,\s*245,\s*0\.88\)/);
    assert.match(css, /\.msj-tiktok-card-metric\s*{[\s\S]*color:\s*#0f7a3d/);
    assert.match(css, /\.msj-tiktok-card-metric-icon\s*{[\s\S]*color:\s*#16a34a/);
    assert.match(css, /\.msj-tiktok-card-metric-icon\[data-icon="warning"\]::before\s*{[\s\S]*content:\s*"!"/);
    assert.match(css, /\.msj-tiktok-card-metrics-left\s*{/);
    assert.match(css, /\.msj-tiktok-card-metrics-right\s*{/);
    assert.match(css, /\.msj-tiktok-card-filter\s*{[\s\S]*position:\s*fixed/);
    assert.match(css, /\.msj-tiktok-card-filter\s*{[\s\S]*color:\s*#0f7a3d/);
    assert.match(css, /\.msj-tiktok-card-filter-trigger\s*{[\s\S]*border-radius:\s*999px/);
    assert.match(css, /\.msj-tiktok-card-filter-title\s*{/);
    assert.match(css, /\.msj-tiktok-card-filter-description\s*{/);
    assert.match(css, /\.msj-tiktok-card-filter-quick\s*{/);
    assert.match(css, /\.msj-tiktok-card-filter-section-title\s*{/);
    assert.match(css, /\.msj-tiktok-card-filter-chip\.is-active\s*{[\s\S]*background:\s*#16a34a/);
    assert.match(css, /\.msj-tiktok-card-filter-secondary\s*,[\s\S]*\.msj-tiktok-card-filter-apply\s*{[\s\S]*background:\s*#16a34a/);
    assert.match(css, /\.msj-tiktok-card-filter-panel\s*{[\s\S]*position:\s*absolute/);
    assert.match(css, /\.msj-tiktok-card-filter-panel\s*{[\s\S]*background:\s*rgba\(236,\s*253,\s*245,\s*0\.96\)/);
    assert.match(css, /\.msj-tiktok-card-filter-help\s*{/);
    assert.match(css, /\.msj-tiktok-card-filter-hidden\s*{[\s\S]*display:\s*none\s*!important/);
    assert.match(source, /CARD_FILTER_HIDDEN_CLASS/);
    assert.match(source, /视频筛选/);
    assert.match(source, /爆款评价/);
    assert.match(source, /排序条件一/);
    assert.match(source, /排序条件二/);
    assert.match(source, /排序条件三/);
    assert.match(source, /最低每小时点赞量/);
    assert.match(source, /最低总点赞量/);
    assert.match(source, /加载更多/);
    assert.doesNotMatch(source, /加载更多并排序/);
    assert.match(source, /TIKTOK_CARD_SORT_FIELD_OPTIONS/);
    assert.match(source, /compareTikTokCardFilterEntries/);
    assert.match(source, /近24小时/);
    assert.match(source, /近7天/);
    assert.match(source, /不限时间/);
    assert.match(source, /发布日期从/);
    assert.match(source, /发布日期到/);
    assert.doesNotMatch(source, /每小时点赞量最大/);
    assert.match(source, /非英内容/);
    assert.match(source, /时长<1分/);
    assert.match(source, /发布>1天/);
    assert.match(source, /createTikTokCardMetricsOverlay/);
    assert.match(source, /getTikTokVideoMetricItems/);
    assert.match(source, /getTikTokWarningLabels/);
    assert.doesNotMatch(source, /getTikTokCardInteractionRateLabel/);
    assert.match(source, /tiktokCaptionAutoOpenEnabled/);
    assert.match(source, /tiktokCaptionFontScale/);
    assert.match(source, /tiktokCaptionDisplayMode/);
    assert.match(source, /tiktokCaptionDetailsHeight/);
    assert.match(source, /tiktokCaptionPanelFrame/);
    assert.match(source, /tiktokCaptionButtonPosition/);
  });
});
